[workspace]
members = [
    "lib",
    "android",
    "ios",
    "test_utils"
]

[workspace.dependencies]
log = "0.4.8"
zingolib = { git="https://github.com/Oscar-Pepper/zingolib", default-features=true, branch = "version_command_for_mobile" }
zingoconfig = { git="https://github.com/Oscar-Pepper/zingolib", default-features=true, branch = "version_command_for_mobile" }

[profile.release]
debug = false

[profile.test]
opt-level = 3
debug = false

[patch.crates-io]
incrementalmerkletree = { git = "https://github.com/zcash/incrementalmerkletree", rev = "bae25ad89c0c192bee625252d2d419bd56638e48" }
shardtree = { git = "https://github.com/zcash/incrementalmerkletree", rev = "bae25ad89c0c192bee625252d2d419bd56638e48" }