[workspace]
members = [
    "lib",
    "android",
    "ios",
    "zingomobile_utils"
]
resolver = "2"

[workspace.dependencies]
log = "0.4.8"
zingolib = { git="https://github.com/zingolabs/zingolib", default-features=true, branch = "stable" }
zingoconfig = { git="https://github.com/zingolabs/zingolib", default-features=true, branch = "stable" }

[profile.release]
debug = false

[profile.test]
opt-level = 3
debug = false

# this is needed to build for IOS simulator
[patch.crates-io]
sodiumoxide = { git = "https://github.com/juanky201271/sodiumoxide", rev = "2f1b91e031199412ec631a3afd571a7df2450981"}
