name: Build regtest

on:
  workflow_call:

jobs:
  check-regtest-cache:
    name: Check regtest cache
    runs-on: macos-12
    outputs:
      cache-found: ${{ steps.set-cache-found.outputs.cache-found }}
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if regtest cache exists
        id: check-regtest-cache
        uses: actions/cache@v3
        with:
          path: |
            rust/regtest/bin
            /home/runner/.zcash-params
          key: regtest
          fail-on-cache-miss: true
          lookup-only: true

      - name: Set cache-found
        id: set-cache-found
        if: ${{ ! cancelled() }}
        run: echo "cache-found=${{ steps.check-regtest-cache.outcome }}" >> $GITHUB_OUTPUT

  build-regtest:
    name: Build regtest
    needs: check-regtest-cache
    if: ${{ needs.check-regtest-cache.outputs.cache-found == 'failure' }}
    runs-on: macos-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies and update certificates
        run: |
          brew install \
          pkg-config \
          m4 \
          autoconf \
          libtool \
          unzip \
          git \
          python3 \
          curl \
          bsdmainutils \
          automake \
          libtinfo5 \
          ca-certificates \
          gcc \
          protobuf-compiler \
          libssl-dev \
          apt-transport-https \
          gnupg2 \
          procps \
          golang
        # build-essential \
        # libc6-dev \ libccd?
        # g++-multilib \
        # ncurses-dev \ ncurses?
        # python3-zmq \ python-yq?
        # zlib1g-dev \ zlib-ng?
        # sudo update-ca-certificates

      - name: Checkout lightwalletd repository
        uses: actions/checkout@v3
        with:
          repository: zcash/lightwalletd
          ref: v0.4.15
          path: lightwalletd

      - name: Build lightwalletd
        run: |
          cd lightwalletd
          make

      - name: Checkout zcash repository
        uses: actions/checkout@v3
        with:
          repository: zcash/zcash
          ref: v5.6.1
          path: zcash

      - name: Build zcash
        run: |
          cd zcash
          ./zcutil/fetch-params.sh
          ./zcutil/clean.sh
          ./zcutil/build.sh -j$(nproc)

      - name: Move regtest binaries
        run: |
          cp ./lightwalletd/lightwalletd ./rust/regtest/bin
          cp ./zcash/src/zcashd ./rust/regtest/bin
          cp ./zcash/src/zcash-cli ./rust/regtest/bin

      - name: Cache regtest
        uses: actions/cache@v3
        with:
          path: |
            rust/regtest/bin
            /home/runner/.zcash-params
          key: regtest

