name: IOS Integration test

on:
  workflow_call:
    inputs:
      timestamp:
        required: true
        type: string
      cache-key:
        required: true
        type: string
    
env:
  CACHE-KEY: ${{ inputs.cache-key }}
  TIMESTAMP: ${{ inputs.timestamp }}
  REPO-OWNER: ${{ github.repository_owner }}

jobs:
  ios-integration-test:
    name: IOS Integration test
    runs-on: macos-13
    steps:
      - name: Set envs for zingolib CI
        if: ${{ contains(github.repository, 'zingolib') }}
        run: echo "REPO-OWNER=zingolabs" >> $GITHUB_ENV
            
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPO-OWNER }}/zingo-mobile

      - name: Native rust cache
        uses: actions/cache/restore@v4
        with:
          path: rust/lib/Generated
          key: native-ios-uniffi-universal-${{ env.CACHE-KEY }}
          fail-on-cache-miss: true

      - name: Copy libs to ios folder
        working-directory: rust/lib/Generated
        run: |
          cp ./*.* ../../../ios

      - name: Yarn Install
        run: |
          yarn

      - name: Pod Install
        working-directory: ios
        run: |
          pod install

      - name: Run integration tests
        working-directory: ios
        run: |
          xcodebuild \
            -project ZingoMobile.xcodeproj \
            -scheme ZingoMobile \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.2' \
            clean build test
